# Generated by Django 2.0.3 on 2018-03-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_auto_20180312_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('referencias', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
    ]
