# Generated by Django 2.0.3 on 2018-03-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasgos',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='rasgos',
            name='persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
